version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: converter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      bash -c "alembic upgrade head
      && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

    volumes:
      - .:/app
      - ./.env.example:/app/.env
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"


volumes:
  pg_data:
  redis_data:
