"""empty message

Revision ID: 7a82afbe3a08
Revises: 
Create Date: 2024-01-03 14:33:20.957206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a82afbe3a08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorite_pairs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('target', sa.String(length=3), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'base', 'target')
    )
    op.create_index(op.f('ix_favorite_pairs_user_id'), 'favorite_pairs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_pairs_user_id'), table_name='favorite_pairs')
    op.drop_table('favorite_pairs')
    op.drop_table('users')
    # ### end Alembic commands ###
